# Generated by Django 4.2.6 on 2023-10-27 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('date_of_creation', models.DateField(default=datetime.date(2023, 10, 27))),
                ('username', models.CharField(default='Q_user', max_length=64)),
                ('user_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('profile_photo_url', models.URLField(default=None, null=True)),
                ('followed_users', models.ManyToManyField(blank=True, to='user.user')),
            ],
        ),
    ]
