# Generated by Django 4.2.6 on 2023-10-27 03:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_usuario_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuarios_relacionados',
        ),
        migrations.AddField(
            model_name='usuario',
            name='seguidores',
            field=models.ManyToManyField(related_name='seguidores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='siguiendo',
            field=models.ManyToManyField(related_name='siguiendo', to=settings.AUTH_USER_MODEL),
        ),
    ]
